src/App.tsx, src/apis/instance.ts, src/apis/userApi.ts, src/pages/Main.tsx, src/pages/Mypage.tsx, src/pages/Room.tsx, src/redux/hooks.ts, src/redux/modules/userSlice.tsx, src/redux/store.ts, src/types/userType.ts, tsconfig.paths.json
- resolves #3 
<br>
-  axios instance/interceptor 설정하기
-  회원정보 관련 API 설정하기
-  redux 설정하기
-  userSlice 설정하기
-  router 설정하기
<br>
- 빼먹은건 없는지 찝찝한 기분,,
- userSlice는 서버 배포되면 다시 수정할 예정,,
=> CHORE: 프로젝트 초기 설정하기

public/index.html, src/components/common/Modal.tsx, src/hooks/useClickAway.ts
- resolves #4 
<br>
- 공통 사용을 위한 Modal Component 추가
- Modal 외부 클릭 이벤트 처리를 위한 useClickAway hook 추가
<br>
=> FEAT: Modal Component 추가

public/index.html, src/components/common/Layout.tsx, src/pages/Main.tsx, src/pages/Mypage.tsx, src/pages/Room.tsx
대략적인 페이지별 컴포넌트 위치 추가
<br>
디자인 및 코드 무시해주세요 ㅎ
=> FEAT: 대략적인 페이지별 컴포넌트 위치 추가

.github/workflows/prod.yml
- resolves #22 
<br>
- S3로의 CI 워크플로우 코드를 작성
<br>
- `.env`의 환경변수 값 자체가 수정된다면 `main`브랜치로 릴리즈하기 전에 반드시 `github repository secret`에서 그 값을 변경해야 한다.
- 새로운 환경변수가 추가되면 워크플로우에도 반영해야 한다
- 이 부분은 작업 `PR` 시 새로운 환경변수가 추가되었다고 언급해주시면 제가 반영하겠습니다.
<br>
- [뭘 했는지 정리해둠](https://velog.io/@pds0309/Day37-Github-actions-S3-CloudFront-Route53%EC%9C%BC%EB%A1%9C-React-CICD%ED%95%98%EA%B8%B0)
=> BUILD: S3로의 CI 워크플로우 코드 작성

src/assets/closeButton.svg, src/components/common/Modal.tsx, src/components/game/CamButton.tsx, src/components/game/MicButton.tsx, src/components/home/CreateGameModal.tsx, src/components/home/LoginModal.tsx, src/components/layout/main/MainLayout.tsx, src/components/mypage/Keyword.tsx, src/pages/Mypage.tsx
- resolves #17
<br>
- 키워드 컴포넌트 추가
- 로그인/방 생성 모달 UI 추가
=> FEAT: 마이페이지, 로그인 모달창, 방 생성 모달창 와이어프레임 기반 UI 구현

src/assets/svg_selectIcon.svg, src/components/common/Modal.tsx, src/components/common/Selection.tsx, src/components/game/GameResultModal.tsx, src/components/game/GameRuleModal.tsx, src/components/home/CreateGameModal.tsx, src/components/home/EnterPrivateRoomModal.tsx, src/components/home/EnterRoomModal.tsx, src/components/home/LoginModal.tsx, src/components/home/ReportBugModal.tsx, src/components/home/UserInfo.tsx, src/components/layout/MainTemplate.tsx, src/components/layout/RoomTemplate.tsx, src/components/mypage/EditProfileModal.tsx, src/constants/options.ts, src/pages/Mypage.tsx
- resolves #33
<br>
- 로그인/방 생성 모달 UI 수정
- 방 참가하기/닉네임 변경/버그 제보 모달 생성
- 게임 규칙/게임 결과 모달 생성
<br>
캐릭터 설정 모달은 아직 와이어프레임 작업 진행중으로 완료시 진행
=> FEAT: 와이어프레임 기반 모달 UI 구현

src/components/common/Selection.tsx, src/components/game/GameRuleToolTip.tsx, src/components/layout/RoomTemplate.tsx
- resolves #43
<br>
- 툴팁 모달창 위치 조정 / 불필요 코드 삭제
- selection 최상위 컴포넌트에 ref 속성 적용하도록 수정
<br>
- 툴팁 모달창 제 화면에선 잘 되는 것 같은데 확인 한번만 부탁드립니다!!
- createportal은 한번 지워봤는데 잘되길래 여기서는 지웠습니답
=> FIX: 게임페이지 툴팁 모달창 위치 수정하기

src/components/game/Cam.tsx, src/components/game/CamUserStatus.tsx, src/components/home/CreateGameModal.tsx, src/components/home/RoomList.tsx, src/components/layout/MainTemplate.tsx, src/hooks/socket/useAuthSocket.ts, src/hooks/socket/useErrorSocket.ts, src/hooks/socket/useStreamUpdateSocket.ts, src/pages/Room.tsx, src/types/gameRoomType.ts
- resolves #52 
<br>
<br>
- isSereteRoom 이라고 오타로 되어있던 것을 그대로 사용하고 있었는데 백엔드에서 수정하여 같이 변경한다.
- 배포를 위해 안쓰는 코드들을 제거한다.
<br>
=> FIX: isSeretRoom 이름 백엔드와 동기화

src/components/common/Selection.tsx, src/components/game/GameResultModal.tsx, src/components/home/EnterPrivateRoomModal.tsx, src/components/home/ReportBugModal.tsx, src/components/mypage/EditProfileModal.tsx, src/components/mypage/Keyword.tsx, src/constants/options.ts
- resolves #82
<br>
추가된 디자인 UI 반영
<br>
- 스코어 모달 디자인 반영
- 버그제보 모달 디자인 반영
- 닉네임 변경 모달 디자인 반영
- 키워드 박스 디자인 반영
<br>
- 스코어 결과창은 일단 이렇게 해놨씁니당 고양이는 등수에 맞는 바 위에 올려놓으면 될 것 같습니당 
- 스코어 모달 사용하실 수 있도록 모달 컴포넌트 수정은 이슈 따로 파서 할게용!!
=> FEAT: 추가된 디자인 UI 반영

src/components/game/CamUserStatus.tsx, src/components/game/LeaveRoomModal.tsx, src/components/layout/RoomTemplate.tsx
- resolves #96
<br>
게임 나가기 확인 모달 추가 및 참여자 캠 닉네임 애니메이션 수정
<br>
- 게임 나가기 확인 모달 추가
- 참여자 캠 닉네임 애니메이션 수정
<br>
alert 개념의 모달이라 box-shadow랑 헤더 부분 빼고 최대한 간단하게 만들었는데 어떤가요?? 의견 남겨주시면 수정하겠습니당
=> FEAT: 게임 나가기 확인 모달 추가 및 참여자 캠 닉네임 애니메이션 수정

.github/workflows/pr.yml, src/components/common/AxisXOverflowedText.tsx, src/components/game/Cam.tsx, src/components/game/CamUserStatus.tsx, src/components/game/PresenterCam.tsx, src/components/home/RoomCard.tsx, src/stories/common/AxisXOverflowedText.stories.tsx, src/stories/game/Cam.stories.tsx, src/stories/home/RoomCard.stories.tsx
- resolves #104 
<br>
자잘자잘
<br>
-  메인 캠 닉네임 ellipsis 설정 제거
- 넘치는 글씨 애니메이션 처리 컴포넌트 분리 후 roocard title에 적용
- Cam, RoomCard 스토리북 추가
- github actions 스토리북 CI 누락된 코드 추가
<br>
- 스토리북 업데이트 되었습니다 이제 코멘트에 링크 뜹니다! 👍 
**애니메이션 글씨 컴포넌트 분리 이유**
- 고양이 머리 위 닉네임에도 사용해야해서
- 중복 코드 제거 및 재사용성 증가
똑같쥬?
=> FIX: 자잘한 수정 및 리팩터링

server/index.js, src/apis/userApi.ts, src/components/home/UserInfo.tsx, src/components/mypage/Keyword.tsx, src/redux/modules/userSlice.ts, src/types/userType.ts
- resolves #98
<br>
회원키워드 조회 json-server 업데이트 및 클라이언트 회원정보 조회 기능 수정, 회원키워드 조회 기능 추가
<br>
- 회원키워드 조회 json-server 업데이트
- 회원정보 조회 기능 수정
- 회원키워드 조회 기능 추가
<br>
키워드 어떻게 보여줄지 디자인이 아직 안나와서 대충 해놨씁니당!!
=> FEAT: 회원키워드 조회 json-server 업데이트 및 클라이언트 회원정보 조회 기능 수정, 회원키워드 조회 기능 추가

.github/workflows/prod.yml, src/hooks/useWebRTC.ts
- resolves #101 
<br>
- STUN만으로 LTE, 공공 와이파이 등의 환경에서 사용자와 미디어 연결을 하지 못하는 현상을 해결하기 위해 TURN서버를 구축한다.
<br>
**클라우드 인스턴스에 coturn turn서버를 구축한다.**
- ec2 서버 하나 띄워서 [coturn](https://github.com/coturn/coturn) 으로 TURN 서버 설정 및 실행
**ssl 및 도메인을 적용한다.**
- lets encrypt 써서 쉽게 적용
**로깅하여 연결되는지 테스트한다.**
- 로그 파일 확인할 수 있게 설정 후 rtc연결 해보고 로그 확인
**애플리케이션에서 사용하는 코드를 작성한다.**
<br>
- 스마트폰 lte와의 교환이 잘 안되던 문제 해결됨
30번 정도 새로고침 했을 때 좀 느리긴 해도 #63 같은 문제 없이 캠이 잘 나오는데 그래도 배포된걸로 확인을 더 해봐야할 것 같습니다
<br>
=> FEAT: TURN서버 구현 #101

src/components/character/Cat.tsx, src/components/character/CatEars.tsx, src/components/character/CatStar.tsx, src/components/character/Rocket.tsx, src/constants/characters.ts, src/stories/character/Cat.stories.tsx
- resolves #93
<br>
고양이 컴포넌트를 추가한다.
<br>
- 고양이를 6마리를 디자인에 맞게 구성한다.
- 고양이 6마리와 로켓 3개를 조합할 수 있다.
- 고양이는 얼굴/얼굴+몸통/얼굴+몸통+로켓으로 표현될 수 있다.
- 고양이와 로켓은 자잘한 애니메이션이 있다.
<br>
- svg로 만들어 rect 한땀한땀 좌표 봐가면서 고양이 신체구조별로 나누어 적절히 컴포넌트화 했습니다
- 작은단위의 rect들로 다 구성되어있다보니 애플망고마냥 구분선이 생겨 `strokeWidth` 를 좀 넓혀 없애는 방법으로 해결해서 상세히 보면 각 사각형들의 크기가 약간씩 다릅니다 ㅠㅠ
<br>
스토리북 꼭 보시와요
<br>
@jn33-dev  @heayounchoi  @dy-p-code  @bsh714-dev
=> FEAT: 야옹이 추가

src/components/home/RoomCard.tsx
=> FIX: 불필요한 import 제거

src/components/home/SetUpInfo.tsx
- resolves #124
<br>
- 닉네임 공백 입력 못하도록 설정
=> FEAT: 닉네임 설정 공백 안되도록 설정

src/components/game/GameRuleToolTip.tsx
- resolves #139
<br>
- 게임 규칙 모달 내용 수정
- 게임 규칙 모달 UI 수정
<br>
내용 수정 원하시면 말씀해주세용!
=> FIX: 게임 규칙 모달 내용 설정

src/components/common/Modal.tsx, src/components/home/LogoutModal.tsx, src/components/layout/Header.tsx, src/components/layout/MainTemplate.tsx, src/components/layout/MyPageTemplate.tsx, src/components/layout/RoomTemplate.tsx
- resolves #137
<br>
- 게임페이지에서 로그아웃 모달 안보이게 설정
- 마이페이지에서 마이페이지 이동 버튼 안보이게 설정
=> FEAT: 마이페이지 로그아웃 모달

src/components/common/Button.tsx, src/components/home/CreateGameModal.tsx, src/components/home/EnterPrivateRoomModal.tsx, src/components/home/SetUpInfo.tsx, src/styles/GlobalStyle.ts, src/styles/theme.ts
- resolves #123
<br>
버튼이 이벤트 시 디자인을 적용한다.
<br>
- 버튼 클릭 디자인 적용
- 버튼 호버 디자인 적용
- 게임방 생성 모달 비밀방 버튼 디자인 적용
- 게임방 생성 모달 버튼 disabled 풀렸을때 깜빡이는 디자인 적용
- 캐릭터 설정 모달 고양이/로켓 버튼 하나씩 클릭 디자인 적용 되도록 설정
<br>
버튼 disabled 풀렸을때 깜빡이는 애니메이션은 피그마에 게임방 생성 모달에만 있어서 거기에만 적용해뒀습니당
=> FEAT: 버튼 이벤트 디자인 적용

src/components/game/Cam.tsx, src/components/game/CamList.tsx, src/components/game/CamUserStatus.tsx, src/components/game/Presenter.tsx, src/components/game/PresenterCam.tsx, src/hooks/useWebRTC.ts
- resolves #128 
<br>
- 캠 껐을 때 UI추가
- 캠 껐을 때 화면 크기 조정
<br>
=> FEAT: 캠 꺼졌을 때 UI 추가

src/components/character/CatOnGame.tsx, src/components/character/CatScore.tsx, src/components/character/ShootingStars.tsx, src/components/character/Star.tsx, src/components/common/StarlightBackground.tsx
- resolves #144 
<br>
<br>
- 고양이 올라갈 때 로켓 빨라지는 모션 시간 짧은 것 수정
- 별똥별 겹치는 부분/너무빠른 것 수정
- 스코어 오르는 속도 수정
<br>
=> FEAT: 애니메이션 컴포넌트 관련 수정

src/hooks/socket/socketInstance.ts, src/hooks/socket/useErrorSocket.ts, src/hooks/socket/useGameUpdateSocket.ts, src/pages/Room.tsx
- resolves #145 
<br>
게임 도중 탈주자에 대한 처리가 필요하다면 핮
<br>
- 방에서 새로고침 시 `beforeunload`로 확인을 안눌렀는데도 소켓 연결이 끊기던 문제 개선
<br>
- 백엔드와 최종적으로 맞춰서 테스트 해보고 리뷰요청 드릴게요
<br>
=> FEAT: 탈주자 처리

src/components/common/Modal.tsx, src/components/game/GameRuleToolTip.tsx, src/components/home/SetUpInfoModal.tsx, src/components/home/SetUpInfoSuccess.tsx
- resolves #153
<br>
- 게임 규칙 모달 위치 조정
- 회원가입 완료시 새로고침 설정
=> FIX: 자잘한 오류 수정

src/components/common/GameButton.tsx, src/components/common/ToastProvider.tsx, src/components/game/CamButton.tsx, src/components/game/CamList.tsx, src/components/game/MicButton.tsx, src/components/game/Presenter.tsx, src/components/game/PresenterKeywordBox.tsx, src/components/home/CreateGameModal.tsx, src/components/home/LoginModal.tsx, src/components/home/ReportBugModal.tsx, src/constants/options.ts, src/hooks/socket/useChatSocket.ts, src/redux/modules/gamePlaySlice.ts, src/redux/modules/playerMediaSlice.ts, src/stories/game/PresenterKeywordBox.stories.tsx, src/types/socketType.ts, src/utils/common.ts
- resolves #150 
<br>
게임 페이지 키워드/캠 목록 개선 및 기타 UI 수정
<br>
- 불필요 UI제거
- 캠 off 상태 고양이 반영
- 플레이어 키워드 정답 관련 처리추가
<br>
=> FEAT: 게임 페이지 키워드/캠 목록 개선 및 기타 UI 수정

src/components/home/SetUpInfoSuccess.tsx, src/hooks/socket/useAuthSocket.ts, src/hooks/socket/useGamePlaySocket.ts, src/hooks/socket/useGameSocket.ts, src/hooks/socket/useGameUpdateSocket.ts, src/hooks/socket/useStreamUpdateSocket.ts, src/hooks/useLocalStream.ts, src/pages/Room.tsx
- resolves #156 
<br>
- 불필요 import 제거
- 불필요 console.log 제거
<br>
=> STYLE: console log 제거

src/components/home/ReportBugModal.tsx
- resolves #160
<br>
버그 제보 api 설정
<br>
토스트 에러 처리로 옮겨놨어용
=> FEAT: 버그 제보 api 설정

src/components/home/ReportBugModal.tsx
=> BUILD: main 배포

src/components/home/ReportBugModal.tsx, src/components/mypage/GrowthTower.tsx
- resolves #167
<br>
- 레벨 1 타워 고양이 0점일때만 보여지는 문제 수정
- 버그 제보 띄어쓰기 안되는 문제 수정
=> FIX: 자잘한 문제 수정

src/components/character/CatOnGame.tsx, src/components/character/CatScore.tsx, src/components/game/ChatLog.tsx, src/components/game/GameResultBarChart.tsx, src/components/game/PlayerCat.tsx, src/stories/character/CatOnGame.stories.tsx, src/stories/character/CatScore.stories.tsx, src/stories/game/GameResultModal.stories.tsx
- resolves #165 
<br>
스코어링이 정상적으로 되지 않던 문제 해결하기
<br>
**점수가 의도와 다르게 비정상적으로 오르는 문제 해결**
- timeout 차이때문에 비정상적으로 올라가는 경우에 대한 처리
**발표시간 종료 후 키워드 토스트 띄우도록 추가**
<br>
=> FIX: 스코어링 관련 문제 해결하기

src/components/home/AnnouncementModal.tsx, src/pages/Main.tsx
- resolves #179
<br>
공지사항 모달 추가
<br>
체크박스 ref 잡는데 시간 좀 걸릴 것 같아서 그냥 온클릭으로 햇습니다
=> FEAT: 공지사항 모달 추가

src/components/game/LeaveRoomModal.tsx
- resolves #176
<br>
- 게임방 나가기 클릭으로 나갈 경우 점수 반영 안되는 문제 수정
=> FIX: 게임방 나가기 클릭으로 나갈 경우 점수 반영 안되는 문제 수정

server/index.js
- resolves #187
<br>
추가 및 수정된 api를 json server에 업데이트 한다.
<br>
- 구글 소셜 로그인 삭제
- 닉네임 중복확인 수정
- 회원정보 수정 추가
- 버그 리포트 추가
- 최초 로그인 식별 추가
<br>
내일 rtk 쿼리로 바꾸려고 json server 업데이트 했습니당
=> FEAT: json server 업데이트

src/components/home/CreateGameModal.tsx, src/hooks/socket/useGameSocket.ts, src/redux/modules/gameRoomSlice.ts, src/types/socketType.ts, src/utils/stroage.ts
- resolves #184 
<br>
비밀번호 있는 방 emit 시 비밀번호를 숫자4자가 아닌 숫자인 문자열 4자를 줄 수 있도록 수정
<br>
=> FIX: 비밀번호 0으로 시작할 경우를 위한 type 수정

src/components/home/AnnouncementModal.tsx, src/components/home/LoginModal.tsx, src/components/home/UserInfo.tsx, src/components/layout/RoomTemplate.tsx, src/pages/Main.tsx
- resolves #185
<br>
컨벤션에 맞게 변수명을 수정하고, new Date()가 컴포넌트에서 바로 실행되지 않도록 수정한다.
<br>
- useState 변수명 수정
- new Date() 실행 위치 수정
- 추가적으로 발견한 카카오 로그인 불필요 상수 렌더링 수정
=> FIX: useState 변수명 수정, new Date() 컴포넌트에서 바로 하지 않도록 수정

src/components/game/ChatLog.tsx
- resolves #189 
<br>
<br>
- 채팅 isComposing 여부 체크를 평가가 아닌 일반챗에 추가
- 공백 없는 긴 채팅이 채팅방 넘어가는 부분 수정
```
word-wrap: break-word;
word-break: break-all;
```
- 채팅방 스크롤바 스타일 추가
=> FIX: 채팅 입력 UI오류 수정

src/components/common/Button.tsx, src/components/common/GameButton.tsx, src/components/game/CamButton.tsx, src/components/game/LeaveRoomModal.tsx, src/components/game/MicButton.tsx, src/components/home/CreateGameModal.tsx, src/components/mypage/GrowthTower.tsx
- 방 나가기 beforeunload 뜨는 문제
- 아이콘 버튼들 focus, hover 이상하게 적용되던 문제
- 게임방 생성 시 비밀번호가 숫자 4자리임을 알려주지 않던 문제
- 캣타워 점수 상한 및 이상한 텍스트가 보이던 문제
=> FIX: 자잘한 UI적인 부분들 수정

src/components/game/Cam.tsx, src/components/game/CamList.tsx, src/components/game/PlayerCat.tsx, src/components/game/PresentationInfo.tsx, src/components/game/Presenter.tsx, src/hooks/useGameTimeCountDown.ts, src/stories/game/Timer.stories.tsx
- resolves #191 
<br>
게임 페이지 캠/마이크 관련 개선, 수정
<br>
**게임 중 음성이 안되는 문제 해결**
- 실제 캠 위치는 발표자가 바뀌면서 계속 바뀌는데 바뀔 때 cam off면 stream을 안넣어서 발생한 문제
**캠/마이크를 입장 시 off상태로 변경**
**게임 타이머 로직 개선**
=> FIX: 게임 페이지 캠/마이크 관련 개선, 수정

README.md
- resolves #62 
<br>
리드미를 작성하라
<br>
**작성 사항**
- 간단 소개
- FE기술스택
- 팀원소개
**필수적으로 추가할 것들**
- 주요기능(사진,움짤 적절히 곁들여서)
- 학습일지 & 트러블 슈팅 링크
**개선할 것**
- 아키텍쳐 추가된 것 반영해야함
=> DOCS: 리드미 1차 작성

src/components/character/CatIcon.tsx, src/components/game/Cam.tsx, src/components/game/CamUserStatus.tsx, src/components/game/PlayerImageHolder.tsx, src/stories/character/CatIcon.stories.tsx
- resolves #199 
<br>
Player Cam status의 비어있던 동글뱅이에 고양이 아이콘 추가
<br>
- 고양이 아이콘 컴포넌트 추가
- 고양이 아이콘을 PlayerImageHolder에 넣도록 추가
<br>
디자이너님이 요구하셨던 고양이를 넣었습니다.
<br>
=> FEAT: Player Cam status에 고양이 아이콘 추가

src/components/game/Cam.tsx
- resolves #210 
<br>
캠 거울모드를 적용했어요
<br>
=> FEAT: 캠 거울모드 적용

src/components/mypage/Keyword.tsx, src/types/userType.ts
- resolves #213
<br>
- 키워드 링크 추가
=> FEAT: 키워드 링크 추가

src/components/home/SetUpInfoSuccess.tsx
- resolves #223
<br>
닉네임 길어질때 웰컴 문구 두줄로 바뀌도록 수정
=> FIX: 닉네임 길어질때 웰컴 모달 UI 수정

src/shared/Router.tsx
- resolves #237 
<br>
<br>
- 없는 path에 대한 메인페이지로의 redirect 설정 추가
<br>
- 별 것 아니지만 진작 처리해줬어야 하는 부분이네여 
<br>
=> FEAT: 없는 페이지에 대한 요청 처리하기
