gachimind/frontend

.eslintrc.json
package-lock.json
package.json
src/App.tsx
src/apis/userApi.ts
src/components/common/Modal.tsx
src/index.tsx
src/redux/hooks.ts
src/redux/modules/userSlice.tsx
src/redux/store.ts

- resolves #7 
<br>
- `npm install -D eslint-plugin-import`
- import 순서 룰을 적용
**순서는 다음과 같습니다**
- 내부모듈(또는 리액트 관련) `EX) react, react-router, react-router-dom`
- 외부 라이브러리 모듈
- 내부 파일 모듈 (type-alias 설정된)
- 내부 컴포넌트 모듈
- 내부 타입 모듈
- `sibiling 등 내부 모듈`
<br>

CHORE: Eslint를 통한 Import 순서 자동 정렬 설정하기

---

src/components/game/Cam.tsx
src/components/game/CamButton.tsx
src/components/game/CamList.tsx
src/components/game/MicButton.tsx
src/components/home/RoomList.tsx
src/constants/socket.ts
src/hooks/socket/useAuthSocket.ts
src/hooks/socket/useGameSocket.ts
src/hooks/socket/useGameUpdateSocket.ts
src/hooks/socket/useStreamUpdateSocket.ts
src/hooks/useLocalStream.ts
src/hooks/useWebRTC.ts
src/pages/Room.tsx
src/redux/modules/playerMediaSlice.ts
src/redux/modules/userMediaSlice.ts
src/redux/store.ts
src/types/gameRoomType.ts

- resolves #12 
<br>
하나의 방에 있는 사용자들 간의 최소한의 미디어 커뮤니케이션이 가능하도록 기능을 구현한다.
<br>
- localMediaStream 처리 추가: 현재 브라우저의 사용자 비디오/오디오 사용
- 방에서 본인의 미디어스트림을 사용
- WebRTC 흐름 추가
- 기본적인 `offer`, `answer`, `ice`를 통해 상호간 연결
- 로컬 비디오/오디오를 사용자가 키고 끌 수 있다.
- 본인의 비디오/오디오 변경 정보는 방의 모두에게 공유된다.
<br>
다른사용자가 들어왔을 때 내 sdp를 준다.
비록 백엔드를 만들며 구현했으나 실제 백엔드 데브 브랜치 코드와의 동기화를 위해 노력해야한다.
<br>
아직  `update-room` 관련 명세 동기화 하나를 해야 하는데 매우 사소한 부분이라 리뷰에는 지장없습니다.
리뷰 승인 후 반영하게 되더라도 이해해주세요!
@jn33-dev

FEAT: WebRTC를 통한 방의 사용자들간 커뮤니케이션

---

src/components/game/CamList.tsx
src/components/game/ChatLog.tsx
src/hooks/socket/useChatSocket.ts
src/hooks/socket/useGameUpdateSocket.ts
src/redux/modules/gameRoomSlice.ts
src/types/chatType.ts
src/types/gameRoomType.ts
src/types/socketType.ts

- resolves #30 
<br>
게임방 참여자 간 채팅 기능 구현
<br>
- 유저들의 입장/퇴장 시 채팅에 알림이 식별되도록 기능 추가
- 유저의 채팅이 모두에게 보여지도록 기능 추가
- 엔터 키로 채팅을 등록할 수 있다.
- 채팅이 많아지면 스크롤이 생긴다.
- 방을 나가면 채팅 기록이 모두 초기화 되도록 설정
<br>
- 스크롤 디자인을 추가해야함

FEAT: 게임방 채팅 구현

---

public/index.html
src/components/common/GlobalLoading.tsx
src/components/home/CreateGameModal.tsx
src/components/home/RoomList.tsx
src/hooks/socket/useGameSocket.ts
src/hooks/useLocalStream.ts
src/pages/Room.tsx
src/redux/modules/userMediaSlice.ts
src/utils/common.ts

- resolves #34 
<br>
분리되어있던 로컬 미디어스트림 처리를 중앙화 하고 준비중임을 보여주도록 글로벌 로딩을 적용
<br>
방 생성 시, 방 목록에서 방 클릭 시 미디어스트림을 각각 처리하도록 되어있던 부분을 중앙화
<br>
**첫 시도 실패**
>  `Room` 페이지 렌더링 시에 로딩을 적용하고 미디어스트림 불러오기
게임 페이지 로직이나 상태 관리가 매우 복잡하여 게임페이지 렌더링 시 미디어스트림을 불러와 webrtc로 네트워크 연결을 모두 하도록 설정하기에는 변경이 많을 것 같고 
시도해보았으나 `offer`한 쪽에서 상대의 미디어를 잘 가져오지 못하는 문제 발생
아마 이미 가짜 스트림을 가져온 상태에서 업데이트가 안되서 그런걸로 예상되며 해결에 시간이 매우 오래걸릴 것이라 판단함.
<br>
**다른 시도 - 다른페이지이용하기**
- 게임을 생성하던 방목록에서 클릭해 들어가던 `/room/:id` 가 아니라 `/?roomId=:id`로 `navigate` 시켰음.
- 해당 쿼리스트링을 인식시켜 미디어스트림을 업데이트하고 `/room/:id`로 이동시키도록 함
- `/room/:id` 로 직접 접근 시 미디어 스트림 로딩 성공 여부를 판단해 아직 가져오지 않았다면  `/?roomId=:id`로 이동시켜 준비하게 함
<br>
**방 생성**
<br>
**방 입장**
<br>
**새로고침**
<br>
한 번에 페이지에서 처리하면 좋을 것 같은데 저의 능력으로는 안되겠네여
미디어스트림을 준비하는 페이지나 창이 따로 없는데 바로 게임 페이지에서 이걸 처리하면 서로 얼굴 교환 시 문제가 자꾸 …

FEAT: 사용자 로컬 미디어스트림 준비 시간 처리를 위한 글로벌 로딩 컴포넌트 추가

---

src/components/game/GameReady.tsx
src/components/game/GameStart.tsx
src/components/game/Presenter.tsx
src/constants/socket.ts
src/hooks/socket/useGameUpdateSocket.ts
src/hooks/useDebounce.ts
src/pages/Room.tsx
src/types/gameRoomType.ts

- resolves #13 
<br>
게입방에 입장해서 게임을 진행하기 까지의 통신을 구현
<br>
- 게임방은 대기/게임 진행중 상태를 가진다.
-  대기 상태의 게임방에서 방장이 아닌 사용자들은 ready를 할 수 있다.
-  방장은 모두가 레디했을 때 게임방을 게임 진행중 상태로 변경시킬 수 있다.
- 레디 버튼은 `debounce`를 적용해 마지막 버튼 클릭의 상태만 서버로 전송되게끔 구현
<br>
- 디자인은 일부러 아예 반영안했습니다. 생 div 생 button
- 레디버튼은 레디하기/레디취소로 계속 글씨가 바뀌는데 실제 반영은 마지막에 되는 괴리감이 아직 있음. 추후 한번 클릭 시 일정 시간동안 못 누르는 방식으로 개선
<br>

FEAT: 게임방 상태를 분리하고 소켓 통신을 적용 #13

---

package-lock.json
package.json
server/authenticationHandler.js
server/index.js
src/App.tsx
src/apis/instance.ts
src/components/common/LoginStatus.tsx
src/components/home/CreateGameModal.tsx
src/components/home/LoginModal.tsx
src/components/home/ReportBugModal.tsx
src/components/home/UserInfo.tsx
src/components/layout/Header.tsx
src/components/layout/MainTemplate.tsx
src/components/layout/PageContainer.tsx
src/components/layout/RoomTemplate.tsx
src/components/mypage/EditProfileModal.tsx
src/hooks/socket/socketInstance.ts
src/pages/Main.tsx
src/pages/Mypage.tsx
src/redux/modules/userSlice.ts
src/shared/Router.tsx
src/utils/getCookie.ts

- resolves #10
<br>
소셜 로그인 기능 구현 및 비인증 상태 레이아웃 추가
<br>
- 소셜 로그인 버튼 클릭 시 로그인 페이지로 이동
- 쿠키 감지, 토큰 저장, 회원정보 조회
- 스토어에 유저 정보 저장
- 비인증 상태 레이아웃 추가
- 버튼 cursor pointer로 변경
<br>
게임 페이지는 setUser reducer가 지워지기 전이라 인증 상태에서도 처음 페이지에 들어갔을때 비인증으로 인식해 메인페이지로 이동되는 문제가 있어 관련 부분 수정하시게 되면 추가 부탁드립니다! 
<br>
- footer 부분 버튼에 cursor가 바뀌지 않는 문제가 있어 다음에 수정할 예정
- 회원정보 조회 시 로딩 페이지 넣으려고 한건 조회가 엄청 빨라서 안넣었어용..!

FEAT: 소셜 로그인 기능 구현

---

src/components/game/CamUserStatus.tsx
src/components/home/CreateGameModal.tsx
src/components/home/RoomCard.tsx
src/components/home/RoomList.tsx
src/components/home/UserInfo.tsx
src/constants/options.ts

- resolves #77
<br>
게임만들기 입력 제한/글자 수 잘리는 부분 애니메이션 추가
<br>
- 게임 페이지 참여자 캠 status 닉네임/메인 페이지 유저 섹션 닉네임 일정 길이 넘어갈 시 애니메이션
- 방제 12자 길이 제한, 일정 길이 넘어갈 시 애니메이션(기본 방제 설정: 가치마인드 한 판 해요)
- 비밀번호 숫자 4자리 제한
- 일반방 생성 가능하게 수
- 카운트 선택지 2개 셀렉트로 수정
<br>
애니메이션을 최대 길이 기준으로 설정해놔서 아래 움짤처럼 길이가 많이 적으면 공백으로 보이는 시간이 있습니다
저거까지 다 설정하면,, 힘드니까 봐주삼,,
+ gif 메이커 뭐 쓰세여?,, 내껀 왤케 화질이 안좋지 ㅠ

FEAT: 게임만들기 입력 제한/글자 수 잘리는 부분 애니메이션 추가

---

src/components/game/GameReady.tsx
src/components/game/GameResultModal.tsx
src/components/game/Presenter.tsx
src/hooks/socket/useGamePlaySocket.ts
src/hooks/useGameTimeCountDown.ts
src/redux/modules/gamePlaySlice.ts

- resolves #75 
<br>
방에서 게임이 종료되었을 때의 처리를 추가한다.
<br>
- 게임 레디 이벤트 emit이 룸 페이지 렌더링 시도되던 부분을 개선
- 게임 턴 모두 종료될 때 게임 플레이 상태를 초기화 하며 알림을 줌
- 게임 턴 모두 종료될 때 결과 모달창을 띄움   
<br>
아직 백엔드쪽 게임 종료 처리 로직이 완성 안되어서 게임 종료 후 바로 재시작은 안됩니다.
게임 진행하면서 자잘하게 수정해야되는 것들은 다른 이슈에서 해결하려고합니다

FEAT: 게임 종료 시 로직, UI처리 추가

---

src/components/game/ChatLog.tsx
src/components/game/PresentationInfo.tsx
src/components/game/Presenter.tsx
src/components/game/ScoreBoard.tsx
src/components/home/CreateGameModal.tsx
src/components/home/RoomCard.tsx
src/components/home/RoomList.tsx
src/constants/socket.ts
src/hooks/socket/useChatSocket.ts
src/hooks/socket/useErrorSocket.ts
src/hooks/socket/useGamePlaySocket.ts
src/hooks/socket/useGameSocket.ts
src/hooks/useWebRTC.ts
src/pages/Main.tsx
src/pages/Room.tsx
src/redux/modules/gameRoomSlice.ts
src/types/gameRoomType.ts
src/utils/common.ts

- resolves #76 
<br>
게임방 관련 일부 로직을 개선하고 게임중일 때 정답 처리를 추가한다.
<br>
<br>
<br>
RoomCard를 children을 가지는게 아니라 room props를 받아서 구현되게끔 리팩터링했습니다. 스타일은 안 건드리고 컴포넌트만 잘 RoomList와 분리했습니다.
방 하나에 대한 로직을 쉽게 처리하려고 분리했습니다.
<br>

FEAT: 게임 진행 관련 로직/UI 추가 및 개선

---

src/components/common/Modal.tsx

- resolves #50 
<br>
어떤 모달에서는 clickAway를 없애거나 뒷배경을 시커멓게해서 사용하고 싶다.
<br>
- 모달 props에 옵셔널 타입으로 배경 clickAway 이벤트를 적용할 지 말지 선택할 수 있도록 함 (기본: clickAway 적용)
- 모달 props에 옵셔널 타입으로 배경 그림자를 적용할 지 말지 선택할 수 있도록 함 (기본: 그림자: on)
<br>
<br>
우선 기본으로 배경 그림자 적용되게 설정했습니다.
모달왜케많나요저희
<br>

REFACTOR: Modal ClickAway 및 뒷 배경 선택적으로 적용할 수 있도록 수정

---

package-lock.json
package.json
src/App.tsx
src/components/game/CamUserStatus.tsx
src/components/game/GameResultModal.tsx
src/components/game/Presenter.tsx
src/components/game/PresenterCam.tsx
src/hooks/socket/useGamePlaySocket.ts
src/redux/modules/gameRoomSlice.ts
src/types/gameRoomType.ts
src/utils/common.ts

- resolves #86 
<br>
게임 결과 그래프에 스코어를 반영하고 캠 UI관련 자잘한 문제를 해결한다.
<br>
- 사용자 수와 사용자의 스코어에 맞춰서 그래프를 적절하게 그린다.
- 그래프에 툴팁으로 부가정보를 표시해준다.
- 메인 발표자 캠 마이크가 켜저도 다른사람에게 보이지 않던 부분 수정
- 메인 캠 크기 조정
- 키워드 언더바라 글자수 식별이 안되는 점 개선
<br>
- 리액트 툴팁 사용
```
npm install react-tooltip
npm install @types/react-toolip -D
```
<br>
- 사람 수에 맞춰서 가운데에 표시하는 건 알고리즘 문제 풀 듯 로직이나 코드가 너무 복잡해질 것 같아서 스코어 내림차순으로 사람 수만큼 표시하게끔 변경해봤는데 어떤가요?
- 어차피 고양이를 올려야 하고 본인여부는 그래프 색을 좀 다르게 표현한다던가 하고 스코어는 그래프 밑에 보여줘도 되지만 보조적인 느낌으로 툴팁도 넣어봤는데 어떤가여? 아이콘 같은 곳에도 좀 쓸 수 있을 것 같아서 설치해봤습니다

FEAT: 게임 결과 그래프에 스코어 반영 및 캠 관련 수정

---

src/components/game/ChatLog.tsx
src/constants/socket.ts
src/hooks/socket/useChatSocket.ts
src/redux/modules/gamePlaySlice.ts

- resolves #95 
<br>
게임에서 발표자의 발표 종료 직후 토론 시간에 플레이어들이 평가를 할 수 있다.
<br>
- 토론 시간에 발표자를 제외한 플레이어들은 채팅으로 [0~5] 점수를 입력해 발표자를 평가를 할 수 있다.
- 평가는 하나의 turn에 한 번만 할 수 있도록 함
<br>
**모달로 안 한 이유**
- 평가는 자유인데 토론 시간 내내 평가할 때 까지 모달을 띄우면 사용자가 불편할 것 같다.
- 토론 시간에 자유롭게 대화 및 채팅하면서 편하게 원하는 시점에 평가를 간단하게 하는 것이 좋아보였다.
<br>
- 이따 회의시간에 여쭤보고 모달로 하자고 하면 다시 되돌리겠습니다

FEAT: 게임 중 Discussion Time에 발표자를 평가하는 기능과 UI를 추가

---

src/components/home/EnterPrivateRoomModal.tsx
src/hooks/useBeforeUnload.ts
src/hooks/usePopState.ts
src/pages/Room.tsx

- resolves #94 
<br>
게임 페이지에서 바로 뒤로가기나 새로고침을 시도하는 것이 어려워져야 한다.
**왜**
- 사용자가 잘못 누를 수도 있다. => 의도치 않은 게임 페이지에서의 이탈을 막고 나가기 버튼으로 나갈 수 있게 유도하는 것
<br>
- before unload hook 추가
- pop state hook 추가
- 게임페이지에 반영
<br>

FEAT: 게임 페이지에서의 새로고침/뒤로가기 처리

---

src/components/game/GameReady.tsx
src/components/game/GameResultModal.tsx
src/components/game/Presenter.tsx
src/hooks/socket/useGameUpdateSocket.ts
src/pages/Room.tsx
src/redux/modules/gameRoomSlice.ts

- resolves #108 
<br>
게임 종료 후 처리에서 발생하는 문제를 처리
<br>
- `GameResultModal에서 루프돌며 그래프 그릴 때 key 누락된 부분 수정
- room page 이탈 시 room상태 clean up
- update-room 이벤트를 받을 때 `game-end`에 대한 room 상태를 별도로 반영하도록 함
- ready 컴포넌트 수정
<br>
**게임 페이지를 이탈해도 게임 room 전역 상태가 그대로 남는 문제~~이걸이제보다니..~~**
**cleanup 넣어서 unmount 시 초기화되도록 해결**
<br>
- 해결하고 또 해결해도 에러는 있네요  이래서 처음부터 아예 잘 생각하고개발해야되나봅니다 ㅎㅎ

FIX: 게임 종료 후 처리에서 발생하는 문제 처리

---

src/hooks/useDuplicatedUserInvalidate.ts
src/pages/Main.tsx
src/pages/Room.tsx

- resolves #119 
<br>
중복 로그인 이벤트  처리 추가
<br>
- 중복 로그인 시 기존 사용자 브라우저의 로그인 상태를 만료시키고 메인페이지로 보낸다.
<br>

FEAT: 중복 로그인 처리 추가

---

src/components/common/GameButton.tsx
src/components/game/GameReady.tsx
src/components/game/GameStart.tsx
src/components/game/Presenter.tsx
src/components/layout/GameButtonContainer.tsx
src/stories/common/GameButton.stories.tsx
src/stories/game/GameReady.stories.tsx

- resolves #120
<br>
게임 페이지의 레디/스타트 UI를 디자인에 맞게 개선한다.
<br>
- Game ready, start를 위한 레이아웃 분리해서 추가
- Game ready, start 버튼 상태에 따라 UI및 설명글 변경되도록 추가
<br>
<br>
- 설명글 괜찮나요?
<br>

FEAT: READY/START UI 개선 

---

src/components/mypage/GrowthTower.tsx

- resolves #131
<br>
- 점수에 맞춰 캣타워를 보여준다.
- 1레벨 600점, 2레벨 1200점, 3레벨 1800점, 4레벨 2400점 기준으로 고양이를 캣타워에 위치시킨다.
<br>
흠 점수가 헷갈리는데 0~600점은 레벨1 타워에 보여주는걸까요 아니면 바닥에 보여주는걸까요??
옵션 1:
0-600: 바닥
601-1200: 레벨1
1201-1800: 레벨2
1801- 2400: 레벨3
2401-: 레벨 4
옵션 2(현재):
0-600: 레벨1
601-1200: 레벨2
1201-1800: 레벨3
1801-: 레벨 4
지금도 예나님이 말씀하신대로 게임을 네번 해야 레벨4를 볼 수 있기는 합니다!
@jn33-dev @bsh714-dev @dy-p-code

FEAT: 사용자 점수에 맞춰 캣타워/고양이 보여주기 추가

---

src/apis/userApi.ts
src/components/home/SetUpInfo.tsx
src/components/home/SetUpInfoModal.tsx
src/components/home/UserInfo.tsx
src/redux/modules/userSlice.ts

- resolves #133
<br>
- 회원정보 수정 기능 추가
- 닉네임 중복 검사 api 수정
- 첫 로그인시 띄우는 정보 수정 모달일 경우 생성하기 클릭 시 웰컴 모달 띄우도록 설정
- 메인 페이지 깜빡임 현상으로 스토리지에 닉네임 저장했던 부분 삭제
<br>
UI에 정보가 들어가는 부분이 많아져서 스토리지에 닉네임 저장했던거 그냥 삭제했습니당,,
깜빡이는 부분이 고양이밖에 없는 것 같아서,, 괜찮지 않을까용?,, 움짤 뒷부분에 새로고침 화면도 있숩니다

FEAT: 회원정보 수정 기능 추가

---

src/components/game/Cam.tsx
src/components/game/CamList.tsx
src/hooks/socket/useGameUpdateSocket.ts
src/hooks/useWebRTC.ts
src/pages/Room.tsx
src/redux/modules/playerMediaSlice.ts
src/redux/modules/userMediaSlice.ts

- resolves #164 
<br>
게임방 상태 변화에 따른 미디어스트림 on/off 동작 문제 해결
<br>
<br>

FIX: 게임방 상태 변화에 따른 미디어스트림 on/off 동작 문제

---

src/components/game/Cam.tsx
src/components/game/CamList.tsx

- resolves #171
<br>
- 방에 입장했을 때 기존유저의 현재 캠/마이크 상태를 받아올 수 있게 한다.
- 캠이 꺼졌을 때 고양이 커버를 추가한다
<br>

FEAT: 방 입장 시 기존 유저들의 캠 상태 반영 #171

---

src/components/game/ChatLog.tsx

- 맥에서 한글 채팅을 마지막으로 입력 시 두번 채팅이 보내지는 문제 해결해보기 
- 직접 테스트해볼 수 없기 때문에 원인이나 방법을 계속 찾아 볼 것

FIX: keydown 시 한글 조합중인지 검사 추가

---

src/components/home/SpecialNotificationModal.tsx
src/hooks/useSpecialNotification.tsx
src/pages/Main.tsx

- resolves #205 
<br>
동적 긴급 알림을 띄울 수 있게 한다.
<br>
- 서버리스 api를 구성
- 메인 페이지에서 긴급공지를 띄워야한다면 내용과 함께 추가
<br>

FEAT: 동적 긴급 알림 띄우기

---

package-lock.json
package.json
src/components/common/CircularProgress.tsx
src/components/game/ChatLog.tsx
src/components/game/PresentEvaluate.tsx
src/components/game/Presenter.tsx
src/components/game/RatingCats.tsx
src/components/layout/GameButtonContainer.tsx
src/hooks/socket/useGameInitiationSocket.ts
src/hooks/useDraggable.ts
src/stories/common/CircularProgress.stories.tsx
src/stories/game/PresentEvaluate.stories.tsx

- resolves #226 
<br>
발표종료 후 토론시간에 하는 평가 시스템 UI 개선
<br>
- 채팅으로 발표자 평가하던 기능을 제거
- 토론 시간에 평가 UI가 나오게끔 추가
- 평가 기능을 평가 UI로 리팩터링
- 평가 창이 일정 시간 이후 닫히도록 추가
- 평가 UI를 드래그 가능하게 하여 선택적으로 발표자 캠을 볼 수 있게 함(`react draggable` 사용)
- 캠 껐을 때 발표자 캠에도 본인 고양이가 나오던 것 수정
<br>
클릭이벤트를 막거나 불필요한 리플로우 리페인트를 없앨 수 있을지 고민해보기
- 스토리북도 추가했습니다
- 사실 채팅창에 평가하는 건 저도 마음에 계속 안들었었기때문에 변경해봤어요 어떤가요? 
<br>

FEAT: 발표종료 후 토론시간에 하는 평가 시스템 개선

---

src/components/game/Presenter.tsx
src/hooks/socket/useChatSocket.ts
src/hooks/socket/useEvaluateSocket.ts

<br>
발표자 평가 시스템 개선 후 채팅이 두번 쳐지던 문제 해결
채팅이 두번 채팅목록에 쌓인다.
채팅 컴포넌트에서만 쓸 줄 알고 `useChatSocket` 마운트 시 `on` 이벤트를 수신하도록 설정했는데 
`evaluate`가 채팅이 아닌 형태로 변경되고 다른 컴포넌트에서 가져와 쓰다보니 `on`이벤트를 두번 수신해서 그렇다.
<br>
- `emit evaluate` 에 대한 책임을 `chat`동작에서 분리

FIX: 발표자 평가 시스템 개선 후 채팅이 두번 쳐지던 문제

---

src/components/common/BubbleContents.tsx
src/components/game/Presenter.tsx
src/components/game/PresenterKeywordBox.tsx
src/stories/common/BubbleContents.stories.tsx
src/types/socketType.ts

- resolves #231 
<br>
게임 진행 시 키워드 힌트를 보여줄 수 있다.
<br>
- 키워드 이벤트 아이콘 및 말풍선 UI 구성
- 발표자가 준비 시간에 힌트를 확인할 수 있다.
- 토론 시간에 모두가 힌트를 확인할 수 있다.
<br>
말풍선 아랫부분에 구분선이 있는데 어떻게 없애야할까요
<br>

FEAT: 게임 진행 시 키워드 힌트 보여주기

---

src/components/home/SetUpInfo.tsx

- resolves #240 
<br>
닉네임 수정 관련 누락된 동작 추가하기
<br>
- 닉네임 변경이 있을 경우 중복확인 해야 수정할 수 있도록 개선 
- 편의성을 위해 닉네임 input 변경 시 메시지 몇 개 추가
**닉네임 중복 체크 안하면 제출 안되게 추가**
**input 변경 시 닉네임 중복체크 상태를 초기화시키고 기존 닉네임이라면 그렇다고 알려주고 아니라면 변경 후 중복체크를 했었는지 잊을 불편함을 없애보고자함**
<br>
진작 확인했어야 하는 것을 놓쳤네요!
<br>

FIX: 닉네임 수정 관련 누락된 동작 추가하기

---

src/components/home/AnnouncementModal.tsx
src/components/home/SpecialNotificationModal.tsx
src/hooks/useSpecialNotification.tsx
src/pages/Main.tsx
src/redux/modules/notificationSlice.ts
src/redux/store.ts

- resolves #238 
<br>
공지 모달이 페이지 이동 시 다시 나오는 문제 처리하기 
<br>
- 공지 클라이언트 상태/리듀서 추가
- 전역 상태 관리로 한 번의 페이지 주기동안은 다시 안 뜨도록 개선
- 공지 모달들에 clickaway 설정
<br>

FIX: 공지 모달이 페이지 이동 시 다시 나오는 문제 처리하기
